spring:
  application:
    name: account
  threads:
    virtual:
      enabled: true

  datasource:
    username: serp
    password: serp
    url: jdbc:postgresql://localhost:5432/serp_account
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  data:
    redis:
      host: localhost
      port: 6379
  kafka:
    bootstrap-servers: localhost:9094
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

app:
    security:
      filter:
        publicUrls:
          - first: /api/v1/auth/register
            second: POST
          - first: /api/v1/auth/login
            second: POST
          - first: /api/v1/auth/introspect
            second: POST
        protectedUrls:
          - url-pattern: /api/public/v1/users
            roles:
              - ADMIN

server:
  port: 8081
  servlet:
    context-path: /account