spring:
  application:
    name: account
  threads:
    virtual:
      enabled: true

  datasource:
    username: serp
    password: serp
    url: jdbc:postgresql://localhost:5432/serp_account
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  data:
    redis:
      host: localhost
      port: 6379
  kafka:
    bootstrap-servers: localhost:9094
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

app:
  security:
    jwt:
      private-key: ${JWT_PRIVATE_KEY}
      public-key: ${JWT_PUBLIC_KEY}
      access-token-expiration: 604800000
      refresh-token-expiration: 604800000
      header: Authorization
      prefix: Bearer
    filter:
      publicUrls:
        - first: /api/v1/auth/login
          second: POST
        - first: /api/v1/auth/register
          second: POST
      protectedUrls:
        - url-pattern: /api/public/v1/users/**
          roles:
            - ADMIN
          permissions:


server:
  port: 8081
  servlet:
    context-path: /account