services:
  serp-redis:
    image: redis:7.2.4-alpine
    container_name: serp-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - serp-network

  serp-postgre-db:
    image: postgres:latest
    container_name: serp-postgre-db
    environment:
      - POSTGRES_USER=serp
      - POSTGRES_PASSWORD=serp
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - serp-network

  kafka:
    image: bitnami/kafka:3.9.0
    container_name: serp-kafka
    hostname: kafka
    ports:
      - '9092:9092'
      - '9094:9094'
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
    volumes:
      - kafka_data:/bitnami/kafka
    networks:
      - serp-network

volumes:
  postgres-data:
    driver: local
  redis-data:
    driver: local
  kafka_data:
    driver: local

networks:
  serp-network:
    driver: bridge